### ISSUE TITLE
[grails 3.3.2] NoClassDefFoundError: ServletRegistrationBean

### ISSUE THREAD

**Issue by ghost** [ondrej-kvasnovsky/grails-vaadin-plugin#64]
I try to migrate to grails 3.3.2 and vaadin 8. Is it possible with this plugin?
 I ran into issues following your nice tutorial at    https://ondrej-kvasnovsky.gitbooks.io/vaadin-on-grails-3/content/command_line.html

My first problem is that it seems like the command gradle vaadin-quickstart does not do anything. So you have to create VaadinConfig.groovy and the UI class yourself.

Second problem is that I get an Exception when trying to run the Hello World application:
`java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/ServletRegistrationBean
  at com.vaadin.grails.VaadinGrailsPlugin$_closure1$_closure2.doCall(VaadinGrailsPlugin.groovy:100)`
Which I don't know how to work around.
I get another exception when applying the workaround from    https://github.com/spring-projects/spring-boot/issues/8186
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vaadinUIServlet0': Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)`

I see there is a branch called _grails3_vaadin8_. Is this plugin still under development?

**Comment by ghost** [comment]
I just found at http://docs.grails.org/3.3.2/guide/upgrading.html

> Spring Boot 1.5.x removes a number of deprecated classes, notably all of the classes within the org.springframework.boot.context.embedded package. If your application is referencing any of the classes within this package you will need to alter your imports to use org.springframework.boot.web.servlet instead.

So I guess the imports have to be adjusted

**Comment by ghost** [comment]
When I follow the tutorial for linked above with grails 3.2.8 I get another exception:
`Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'prodModeServletContextInitializer': Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [java.util.LinkedHashMap] to required type [java.util.Map]: Failed to convert value of type 'java.util.LinkedHashMap' to required type 'java.util.Map'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'groovy.util.ConfigObject' to required type 'java.lang.String': no matching editors or conversion strategy found`

But the error only appears if I have a VaadinConfig.groovy so I guess that there is an issue with either the grails-vaadin-plugin or my setup :(

**Comment by ondrej-kvasnovsky** [comment]
Thanks for reporting the issue, I am going to check it out in couple of hours. Will let you know how it goes.

**Comment by ghost** [comment]
Nice to hear. In the meantime if anyone is looking for a solution: Vaadin 8 works in Grails 3.3.2 with `vaadin-spring-boot-starter` plugin. To configure add in **build.gradle**
```
dependencies {
    ...
    compile "com.vaadin:vaadin-spring-boot-starter:3.0.0"
}
```
Then annotate your UI classes with `@SpringUI(path="/PATH")`, where _PATH_ is the desired URL to open the site (e.g. "/myapp").
This replaces the configuration in UrlMappings.groovy, so that any mappings in this file can be removed.

Finally the package in which the UI class is stored must be configured in **application.yml** as follows:
```
grails:
    spring:
        bean:
            packages:
                - PACKAGE_OF_VAADIN_UI_CLASS
```

When running your project, you should be able to open your Vaadin UI under the URL from the annotation. Note that this approach is not using the `grails-vaadin-plugin` plugin and thus VaadinConfig.groovy is not required.

**Comment by ondrej-kvasnovsky** [comment]
It is fixed, please use the latest versions available: https://bintray.com/ondrej-kvasnovsky/plugins

[https://www.dropbox.com/s/dnzgeb8m0g8b7in/vaadin-test.zip?dl=0](demo-project) that is using latest versions

**Comment by ghost** [comment]
Thank you very much. Unfortunately I get another exception when using the new import:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'prodModeServletContextInitializer': Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [java.util.LinkedHashMap] to required type [java.util.Map]: Failed to convert value of type 'java.util.LinkedHashMap' to required type 'java.util.Map'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'groovy.util.ConfigObject' to required type 'java.lang.String': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:387)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at trustcenter.Application.main(Application.groovy:8)
```

**Comment by ondrej-kvasnovsky** [comment]
I will need to know more about this issue. Do you think you could share a project that would replicate this issue?

**Comment by ghost** [comment]
[Vaadin8_Grails_3_3_2.zip](https://github.com/ondrej-kvasnovsky/grails-vaadin-plugin/files/1801936/Vaadin8_Grails_3_3_2.zip)

This is a new Grails project created using IntelliJ. I modified the **build.gradle** as explained in the tutorial. Besides that I only added HelloWorld.groovy in **src/main/groovy/app** and **VaadinConfig.groovy**

**Comment by ondrej-kvasnovsky** [comment]
@astange-cor I have tried to run your project and here are my observations: 
- make sure you are using latest version of plugin and library: https://bintray.com/ondrej-kvasnovsky/plugins 
- make sure VaadinConfig.groovy contains needed configuration (this is tricky, will try to improve it and provide some defaults) -> this caused the issue in your example
```
vaadin {
    mapping = [
           "/hw": "app.HelloWorld"
    ]
    productionMode = false
    openSessionInViewFilter = 'org.springframework.orm.hibernate5.support.OpenSessionInViewFilter'
    asyncSupported = true
}

environments {
    production {
        vaadin {
            productionMode = true
        }
    }
}
```
- also, I would suggest to use latest version of Grails, GORM and Gradle

Here is your sample project and it is working now: 
[Vaadin8_Grails_3_3_2 working.zip](https://github.com/ondrej-kvasnovsky/grails-vaadin-plugin/files/1805554/Vaadin8_Grails_3_3_2.working.zip)

Let me know what you think.

**Comment by ghost** [comment]
Thanks it works! I didn't had a valid config because the automatic setup project for it didn't work. I assumed mine was minimal.
